### ISSUE TITLE
Add different ability categories such as Heroic, Signature, Villain Action

### ISSUE THREAD

**Issue by cdverrett94** [MetaMorphic-Digital/draw-steel#114]
Currently no way to indicate that an ability is a heroic or signature ability. Villain actions could be included in this as well. Would denoting free strikes be here as well?

**Comment by JPMeehan** [comment]
Probably yeah, some kind of "category" property would be appropriate.

**Comment by cdverrett94** [comment]
Sounds good. I'll take a look at adding that today if I can. If not, then later this week. 

I'll add it to the data model and add it to the abilities config.
