### ISSUE TITLE
Implement _applyChangeMultiply, _applyChangeUpgrade, and _applyChangeDowngrade for FormulaField

### ISSUE THREAD

**Issue by JPMeehan** [MetaMorphic-Digital/draw-steel#32]
In `src/module/data/helpers.mjs`, FormulaField currently only has _applyChangeAdd implemented.

**Comment by krbz999** [comment]
This seems to have been copied wholesale from dnd5e. It was recently updated here: `https://github.com/foundryvtt/dnd5e/pull/4144/files`

Also note that the `Roll.validate` method is not doing anything (see `https://github.com/foundryvtt/dnd5e/issues/4202`).
