### ISSUE TITLE
Update Keywords

### ISSUE THREAD

**Issue by JPMeehan** [MetaMorphic-Digital/draw-steel#61]
Remove resistance, add strike

**Comment by cdverrett94** [comment]
Should class specific ability keywords be added as well? Elementalist has a keyword for the element types (Earth, Fire, Green, Rot, Void), Fury has Animal, Talent has one for its subclasses (Animapathy, Chronopathy, Cryokinesis, Metamorphosis, Pyrokinesis, Resopathy, Telekinesis, Telepathy), Troubador has Routine.

It's possible I missed some others as well.

**Comment by JPMeehan** [comment]
> Should class specific ability keywords be added as well? Elementalist has a keyword for the element types (Earth, Fire, Green, Rot, Void), Fury has Animal, Talent has one for its subclasses (Animapathy, Chronopathy, Cryokinesis, Metamorphosis, Pyrokinesis, Resopathy, Telekinesis, Telepathy), Troubador has Routine.
> 
> It's possible I missed some others as well.

I think the correct solution is 
1. Yes
2. And add some `group` property that all of the options work in.

It may be appropriate to refactor the `keywords` CONFIG object to be more like `skills` with the opt groups and the like. The non-class specific keywords should be ungrouped, keeping them at the top, and then all of the class ones are grouped by class.

**Comment by cdverrett94** [comment]
Sounds good. Where should the class localizations go in en.json. DRAW_STEEL.Classes?

I can take this one though if you want to add the assignment.

**Comment by JPMeehan** [comment]
> Sounds good. Where should the class localizations go in en.json. DRAW_STEEL.Classes?
> 
> I can take this one though if you want to add the assignment.

Honestly `"DRAW_STEEL.Item.Ability.KeywordGroups` is probably fine, since these groups may not always be tied to classes.
