### ISSUE TITLE
Wrong css link in system.json

### ISSUE THREAD

**Issue by kyaEH** [MetaMorphic-Digital/draw-steel#78]
system.json line 71
Before
```js
"styles": ["css/draw-steel.css"],
```
After
```js
"styles": ["src/scss/draw-steel.scss"],
```

**Comment by JPMeehan** [comment]
You need to run `npm ci` then `npm run build:css`

**Comment by JPMeehan** [comment]
Correction: I forgot we had a postinstall script to handle the build, please review [CONTRIBUTING.md](../blob/main/CONTRIBUTING.md)
