### ISSUE TITLE
Add characteristic(s) to ability power rolls 

### ISSUE THREAD

**Issue by cdverrett94** [MetaMorphic-Digital/draw-steel#92]
Need to define which characteristic(s) are used for the power roll. Some abilities allow a choice between multiple. Would need to determine the highest score to use when rolling and for damage.

**Comment by JPMeehan** [comment]
Yeah probably need a "roll bonus" field or something.

**Comment by cdverrett94** [comment]
> Yeah probably need a "roll bonus" field or something.

Yeah, need to add a field for if the characteristic should be added to damage or not. I've done a PR just for adding the field to the data model and sheet. If approved, I can follow up with adding the extra functionality.

**Comment by cdverrett94** [comment]
I've handled this one.
